---
- hosts: all
  vars:
    do_api_key: "APIKEY"
    do_ssh_key_id: "KEYID"

  tasks:
    - name: Create a new DO droplet
      digital_ocean_droplet:
        state: present
        name: do-test-droplet
        oauth_token: "{{ do_api_key }}"
        ssh_keys: "{{ do_ssh_key_id }}"
        size: 2gb
        region: ams3
        image: ubuntu-18-04-x64
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
